const entityDict = {
    "Événement": [
      "Mai 68",
      "La bataille de Stalingrad",
      "La bataille de Valmy",
      "La bataille de Verdun",
      "La Commune de Paris",
      "La conférence de Yalta",
      "L'affaire Dreyfus",
      "La Fronde",
      "La fuite de Varennes",
      "La guerre civile espagnole",
      "La guerre de Cent Ans",
      "La guerre de Trente Ans",
      "La Libération de Paris",
      "La Première Guerre mondiale",
      "La prise de la Bastille",
      "La Renaissance",
      "La Résistance française",
      "La Révolution française",
      "La révolution russe",
      "L'armistice de 1918",
      "La Seconde Guerre mondiale",
      "Le Front populaire",
      "Le Moyen Âge",
      "L'Empire romain",
      "Les Bourbons"
    ],
    "Lieu": [
      "roumanie",
      "japon",
      "le havre",
      "maroc",
      "barcelone",
      "normandie",
      "strasbourg",
      "portugal",
      "venise",
      "pologne",
      "canada",
      "madrid",
      "mayotte",
      "nice",
      "italie",
      "montpellier",
      "rome",
      "caen",
      "londres",
      "mont-saint-michel",
      "arabie",
      "toulouse",
      "angers",
      "metz",
      "la réunion",
      "dunkerque",
      "nouvelle-calédonie",
      "irlande",
      "guadeloupe",
      "russie",
      "turquie",
      "paris",
      "rennes",
      "bretagne",
      "perpignan",
      "espagne",
      "brésil",
      "provins",
      "danemark",
      "moscou",
      "bulgarie",
      "fontainebleau",
      "martinique",
      "alger",
      "ukraine",
      "casablanca",
      "corée",
      "aix-en-provence",
      "belgique",
      "meudon",
      "orléans",
      "corse",
      "cholet",
      "chartres",
      "pérou",
      "guyane",
      "versailles",
      "lisbonne",
      "allemagne",
      "colombie",
      "chili",
      "argentine"
    ],
    "Périodique": [
      "nîmes",
      "Journal de Paris",
      "Journal des débats",
      "La Croix",
      "La Gazette",
      "La Justice",
      "La Lanterne",
      "La Presse",
      "La Revue du monde noir",
      "L'Aurore",
      "Le Figaro",
      "Le Matin",
      "Le Monde",
      "Le Petit Journal",
      "Le Petit Parisien",
      "Le Populaire",
      "L'Equipe",
      "Le Siècle",
      "Le Temps",
      "L'Ouest-Eclair",
      "L'Univers",
      "L'Univers illustré",
      "Marie-Claire",
      "Mercure de France"
    ],
    "Personne": [
      "claude monet",
      "marie-antoinette",
      "camille claudel",
      "karl marx",
      "victor hugo",
      "henri iv",
      "charles cros",
      "théophile gautier",
      "william shakespeare",
      "jean de la bruyère",
      "joseph staline",
      "jules verne",
      "colette",
      "louis pasteur",
      "charles perrault",
      "guillaume apollinaire",
      "pétrarque",
      "thucydide",
      "aristote",
      "bernard de fontenelle",
      "saint louis",
      "lautréamont",
      "polybe",
      "eugène sue",
      "jean-jacques rousseau",
      "louise michel",
      "jules vallès",
      "alphonse allais",
      "albert einstein",
      "jean fouquet",
      "napoléon ier",
      "claude debussy",
      "alphonse daudet",
      "raymond roussel",
      "blaise pascal",
      "charles darwin",
      "george sand",
      "giacomo casanova",
      "alexis de tocqueville",
      "louis-sébastien mercier",
      "alfred de musset",
      "louis xv",
      "arthur rimbaud",
      "sénèque",
      "frédéric chopin",
      "rené descartes",
      "pierre de ronsard",
      "charles dickens",
      "edgar degas",
      "molière",
      "jean jaurès",
      "marcel proust",
      "hans christian andersen",
      "judith gautier",
      "eugène atget",
      "gottfried wilhelm leibniz",
      "françois rabelais",
      "charles de gaulle",
      "marco polo",
      "martin luther",
      "jules simon",
      "pierre-joseph proudhon",
      "prosper mérimée",
      "louis xiii",
      "jane austen",
      "alfred jarry",
      "louis xiv",
      "friedrich nietzsche",
      "denis diderot",
      "henri le secq",
      "maximilien de robespierre",
      "eugène delacroix",
      "sigmund freud",
      "marc de montifaud",
      "jean-philippe rameau",
      "joachim du bellay",
      "paul verlaine",
      "voltaire",
      "georges simenon",
      "edgar allan poe",
      "christine de pizan",
      "vincent van gogh",
      "jean-jacques lequeu",
      "paul valéry",
      "napoléon iii",
      "gustave flaubert",
      "guy de maupassant",
      "cicéron",
      "stendhal",
      "nostradamus",
      "emmanuel kant",
      "maurice maeterlinck",
      "louis xvi",
      "robert louis stevenson",
      "marie curie",
      "ovide",
      "jean de la fontaine",
      "giuseppe verdi",
      "honoré de balzac",
      "léonard de vinci",
      "octave mirbeau",
      "pierre-augustin caron de beaumarchais",
      "baruch spinoza",
      "dante alighieri",
      "jean racine",
      "françois ier",
      "platon",
      "gérard de nerval",
      "françois-rené de chateaubriand",
      "montesquieu",
      "flora tristan",
      "émile zola",
      "oscar wilde",
      "homère",
      "charles baudelaire",
      "ludwig van beethoven",
      "marquis de sade",
      "pablo picasso",
      "jacques-bénigne bossuet"
    ],
    "Thème": [
      "Orientalisme",
      "Pointillisme",
      "Portrait",
      "Réalisme",
      "Romantisme",
      "Rosa Bonheur",
      "Symbolisme",
      "Futurisme",
      "Impressionnisme",
      "Japonisme",
      "Sorcellerie",
      "Surréalisme",
      "Bande Dessinée",
      "Esclavage",
      "Art Nouveau"
    ],
    "Œuvre": [
      "bible",
      "les fleurs du mal",
      "ancien testament",
      "la princesse de clèves",
      "roman de la rose",
      "journal officiel",
      "le petit chaperon rouge",
      "le cid",
      "fables de la fontaine",
      "la marseillaise",
      "la légende dorée",
      "revue archéologique",
      "roman de renart",
      "les métamorphoses",
      "l'odyssée",
      "les trois mousquetaires",
      "roméo et juliette",
      "don quichotte",
      "la belle et la bête",
      "les liaisons dangereuses",
      "les mille et une nuits",
      "les misérables",
      "cendrillon",
      "cartes de cassini",
      "bulletin des lois",
      "candide",
      "estampes japonaises",
      "coran",
      "l'aurore",
      "alice au pays des merveilles",
      "phèdre",
      "code civil",
      "danse macabre",
      "cyrano de bergerac",
      "le rouge et le noir",
      "robinson crusoé"
    ],
  };
  
  export default entityDict;