import random
import time

french_poetic_sentences = [
    "La lune caresse l'onde d'un éclat argenté.",
    "Les étoiles dansent au rythme des cieux infinis.",
    "L'aube tisse des rêves dans un voile de lumière.",
    "Le vent soupire des secrets au creux des vallées.",
    "Sous l'ombre des pins, la mer murmure doucement.",
    "Chaque feuille raconte l'histoire du vent.",
    "Le silence des montagnes écoute le chant du monde.",
    "Une rose éclot, portant l'espoir du jour naissant.",
    "L'éternité se cache dans un instant fugace.",
    "Les nuages dessinent des poèmes dans le ciel.",
    "La rivière fredonne une mélodie éternelle.",
    "Un souffle léger porte l'odeur des champs en fleurs.",
    "Les ombres dansent au clair de la lune.",
    "Les cieux s'embrasent sous l'éclat du crépuscule.",
    "Chaque goutte de rosée est une larme d'étoile.",
    "Les chemins se perdent dans la brume de l'aube.",
    "Une colline verte garde les souvenirs des âges.",
    "Les vagues s'écrasent, écrivant des histoires éphémères.",
    "L'ombre d'un arbre abrite des rêves oubliés.",
    "L'air d'été chante des souvenirs d'enfance.",
    "Le parfum du lilas danse dans le vent printanier.",
    "La mer embrasse l'horizon d'une ligne éternelle.",
    "Sous le ciel d'orage, la terre attend son apaisement.",
    "Les reflets dorés du soleil parent le monde d'or.",
    "La pluie danse sur les toits comme une symphonie douce.",
    "Chaque étoile est une promesse de l'infini.",
    "Les dunes chantent sous le souffle brûlant du désert.",
    "Une rivière scintille, miroir d'un ciel d'azur.",
    "La nuit abrite les rêves que le jour ne voit jamais.",
    "Le vent emporte les paroles que nul ne peut entendre.",
    "Une simple fleur défie la rudesse du roc.",
    "L'univers respire au rythme de l'invisible.",
    "Une barque solitaire dérive sous le ciel étoilé.",
    "Les murmures des arbres sont des poèmes sans fin.",
    "La lune veille sur les âmes perdues des forêts.",
    "L'écho des montagnes renvoie les chants oubliés.",
    "Les coquelicots dansent au vent, fragiles et éclatants.",
    "Les étoiles filantes tracent des espoirs dans la nuit.",
    "La lumière du matin réveille le silence endormi.",
    "Chaque ombre raconte l'histoire de sa lumière.",
    "Le monde dort sous un manteau de neige scintillant.",
    "Une source claire chante la vie dans le silence.",
    "La nuit noire est un écrin pour les rêves dorés.",
    "Un papillon effleure l'éternité en un battement d'ailes.",
    "Les champs dorés murmurent sous le soleil d'août.",
    "L'horizon embrasse le ciel dans un secret éternel.",
    "L'ombre d'une colline protège les secrets du passé.",
    "Une luciole éclaire les chemins du crépuscule.",
    "L'air du soir porte des souvenirs d'amour.",
    "Une brise d'été caresse les champs endormis.",
    "L'océan porte le reflet du ciel dans son cœur.",
    "Le parfum des cerisiers en fleurs emplit l'air de poésie.",
    "Une étoile solitaire brille dans l'immensité noire.",
    "Les nuages s'étirent comme des rêves endormis.",
    "Chaque goutte de pluie contient un morceau du ciel.",
    "Les collines ondulent comme des vagues figées.",
    "Une feuille d'automne danse dans le vent léger.",
    "Les éclairs fendent la nuit de lumière fugace.",
    "Une ruelle pavée murmure des souvenirs anciens.",
    "La pluie d'été embrasse la terre d'un amour bref.",
    "Une étoile de mer repose, gardienne des secrets océaniques.",
    "Les reflets des lacs chantent des hymnes à la paix.",
    "La forêt murmure des contes au cœur des âmes perdues.",
    "Chaque goutte de rosée brille comme un joyau.",
    "La lune veille sur les secrets des amants.",
    "Les étoiles filantes portent des vœux éternels.",
    "Une prairie fleurie danse sous un ciel sans nuages.",
    "Les vagues saluent la plage dans une étreinte sans fin.",
    "Les brumes du matin enveloppent le monde d’un voile mystique.",
    "Une chouette veille, gardienne de la nuit silencieuse.",
    "Les feuilles mortes racontent l'histoire de l'été.",
    "L'horizon s'efface dans un soupir d'infini.",
    "Une barque endormie berce des rêves de marins.",
    "Les étoiles tissent des contes au fil de la nuit.",
    "Chaque souffle de vent caresse la joue du temps.",
    "Les montagnes dorment sous un manteau de brume.",
    "Une fleur sauvage défie l'oubli de la forêt.",
    "Le ciel d'hiver chante des hymnes à la solitude.",
    "Les eaux calmes des lacs renferment mille secrets.",
    "Une colline perdue se pare de fleurs oubliées.",
    "Le soleil couchant peint des tableaux éphémères.",
    "Une plume d'oiseau flotte dans l'air tranquille.",
    "Les étoiles sont les lanternes de l'éternité.",
    "La rosée du matin rafraîchit les rêves de la nuit.",
    "Les champs de lavande s'étendent comme des vagues violettes.",
    "Un ruisseau éclatant serpente entre les pierres.",
    "Les nuages tissent des poèmes dans le ciel.",
    "L'ombre des bois abrite la sagesse du monde.",
    "La lumière s'étire, douce et dorée, au crépuscule.",
    "Les cendres du feu chantent des adieux silencieux.",
    "Une étoile solitaire guide les âmes perdues.",
    "Les bruits de la mer résonnent comme des chants d'adieu.",
    "Une feuille froissée porte les souvenirs de l'été.",
    "Le ciel s'embrase d'un dernier éclat au crépuscule.",
    "Une larme silencieuse roule sur la joue de la nuit.",
    "L'éclat de l'aurore réveille le silence des rêves.",
    "Un souffle léger soulève les graines du futur.",
    "Les ombres du soir caressent les contours du monde.",
    "Une colombe solitaire traverse un ciel infini.",
    "La vie danse, fragile et belle, au bord du néant."
]

def fetch_random_french_sentences(num):
    random.shuffle(french_poetic_sentences)
    time.sleep(2)
    if num == 1:
        return french_poetic_sentences[0]
    else:
        return french_poetic_sentences[:num]